---
version: 2

jobs:
  release:
    docker:
      - image: girder/girder_test:latest-py3
    working_directory: /home/circleci/project
    steps:
      - checkout:
          path: girder
      - run:
          name: Publish python packages
          command: tox -e release
          working_directory: girder

workflows:
  version: 2
  test_all:
    jobs:
      - release:
          filters:
            tags:
              only: /^v[0-9]+.*/
            branches:
              only: master
